export const ActionTypes = {
    GET_CART_ITEMS_NUMBERS: "GET_CART_ITEMS_NUMBERS",
    GET_CART_ITEMS: "GET_CART_ITEMS",
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_FROM_CART: "DELETE_FROM_CART",
    UPDATE_CART_ITEM: "UPDATE_CART_ITEM",
    CLEAR_CART: "CLEAR_CART",
    INCREMENT_CART_ITEM: "INCREMENT_CART_ITEM",
    DECREMENT_CART_ITEM: "DECREMENT_CART_ITEM",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    
    // Auth actions
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT"
};