export const ActionTypes = {
    GET_CART_ITEMS_NUMBERS: "GET_CART_ITEMS_NUMBERS",
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_FROM_CART: "DELETE_FROM_CART",
    UPDATE_CART_ITEM: "UPDATE_CART_ITEM",
    CLEAR_CART: "CLEAR_CART"
};